# .github/workflows/parallel.yml
name: End-to-end tests parallel
on:
  push:
jobs:
  batch:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        batch: ['1', '2', '3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:batch-${{ matrix.batch }}
